In [2]:
# import dependencies
import pandas as pd
import numpy as np

In [3]:
# import source data files

regions = pd.read_csv("raw_data/regions.csv")

od_2014 = pd.read_csv("raw_data/OD_2013_2014.csv")
od_2015 = pd.read_csv("raw_data/OD_2015.csv")
od_2016 = pd.read_csv("raw_data/OD_2016.csv")
od_2017 = pd.read_csv("raw_data/OD_2017.csv")

# import population data
pop = pd.read_csv("raw_data/Pop_2013-2017.csv")

# import perscription data
rx_2013 = pd.read_csv("raw_data/RX_2013.csv")
rx_2014 = pd.read_csv("raw_data/RX_2014.csv")
rx_2015 = pd.read_csv("raw_data/RX_2015.csv")
rx_2016 = pd.read_csv("raw_data/RX_2016.csv")
rx_2017 = pd.read_csv("raw_data/RX_2017.csv")

In [6]:
# rename columns for index on merge

master_df = pd.merge(regions, od_2014, on="State")
master_df = pd.merge(master_df, od_2015, on="State")
master_df.head()

,State,Region,2014Rate,2014Number,2014Range,2013Rate,2013Number,2013Range,Change,Significant,Range,Rate,Number
0,AK,Far West,16.8,124,16.1 to 18.5,14.4,105,13.6 to 16.0,16.7,Not Significant,13.6 to 16.0,16.0,122
1,AL,Southeast,15.2,723,13.6 to 16.0,12.7,598,11.1 to 13.5,19.7,Significant,13.6 to 16.0,15.7,736
2,AR,Southeast,12.6,356,11.1 to 13.5,11.1,319,11.1 to 13.5,13.5,Not Significant,13.6 to 16.0,13.8,392
3,AZ,Southwest,18.2,"1,211",16.1 to 18.5,18.7,"1,222",18.6 to 21.0,-2.7,Not Significant,18.6 to 21.0,19.0,"1,274"
4,CA,Far West,11.1,"4,521",11.1 to 13.5,11.1,"4,452",11.1 to 13.5,0.0,Not Significant,11.1 to 13.5,11.3,"4,659"