In [7]:
# import dependencies
import pandas as pd
import numpy as np

In [8]:
# import source data files

regions = pd.read_csv("raw_data/regions.csv")

od_2014 = pd.read_csv("raw_data/OD_2013_2014.csv")
od_2015 = pd.read_csv("raw_data/OD_2015.csv")
od_2016 = pd.read_csv("raw_data/OD_2016.csv")
od_2017 = pd.read_csv("raw_data/OD_2017.csv")

# import perscription data
rx_2013 = pd.read_csv("raw_data/RX_2013.csv")
rx_2014 = pd.read_csv("raw_data/RX_2014.csv")
rx_2015 = pd.read_csv("raw_data/RX_2015.csv")
rx_2016 = pd.read_csv("raw_data/RX_2016.csv")
rx_2017 = pd.read_csv("raw_data/RX_2017.csv")

# import population data
pop = pd.read_csv("raw_data/pop_2010-2018.csv")

In [3]:
# rename columns for index on merge
od_2014 = od_2014.rename(columns={"2014Number":"OD_2014", "2013Number":"OD_2013"})
od_2015 = od_2015.rename(columns={"Number":"OD_2015"})
od_2016 = od_2016.rename(columns={"number":"OD_2016"})
od_2017 = od_2017.rename(columns={"number":"OD_2017"})
rx_2013 = rx_2013.rename(columns={"State":"State_Name", "State ABBR":"State", "2013 Prescribing Rate":"RX_2013"})
rx_2014 = rx_2014.rename(columns={"State":"State_Name", "State ABBR":"State", "2014 Prescribing Rate":"RX_2014"})
rx_2015 = rx_2015.rename(columns={"State":"State_Name", "State ABBR":"State", "2015 Prescribing Rate":"RX_2015"})
rx_2016 = rx_2016.rename(columns={"State":"State_Name", "State ABBR":"State", "2016 Prescribing Rate":"RX_2016"})
rx_2017 = rx_2017.rename(columns={"State":"State_Name", "Abbreviation":"State", "Year 2017":"RX_2017"})

pop = pop.rename(columns={"table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)":"State",
                         'Unnamed: 6':'Pop_2013', 'Unnamed: 7':'Pop_2014', 'Unnamed: 8':'Pop_2015', 'Unnamed: 9':'Pop_2016', 'Unnamed: 10':'Pop_2017'})
pop = pop.replace({'.Alabama': 'AL', '.Alaska': 'AK', '.Arizona': 'AZ','.Arkansas': 'AR','.California': 'CA',
                    '.Colorado': 'CO','.Connecticut': 'CT','.Delaware': 'DE','.District of Columbia': 'DC',
                    '.Florida': 'FL','.Georgia': 'GA','.Hawaii': 'HI','.Idaho': 'ID','.Illinois': 'IL',
                    '.Indiana': 'IN','.Iowa': 'IA','.Kansas': 'KS','.Kentucky': 'KY','.Louisiana':'LA',
                    '.Maine': 'ME','.Maryland':'MD','.Massachusetts':'MA','.Michigan':'MI', '.Minnesota':'MN',
                    '.Mississippi':'MS','.Missouri':'MO','.Montana':'MT','.Nebraska':'NE','.Nevada':'NV',
                    '.New Hampshire':'NH','.New Jersey':'NJ','.New Mexico':'NM','.New York':'NY',
                    '.North Carolina':'NC','.North Dakota':'ND','.Ohio':'OH','.Oklahoma':'OK',
                    '.Oregon':'OR','.Pennsylvania':'PA','.Rhode Island':'RI','.South Carolina':'SC','.South Dakota':'SD',
                    '.Tennessee':'TN','.Texas':'TX','.Utah':'UT','.Vermont':'VT','.Virginia':'VA','.Washington':'WA',
                    '.West Virginia':'WV','.Wisconsin':'WI','.Wyoming':'WY'})

In [4]:
# merge data for combined dataframe

master_df = pd.merge(regions, od_2014, on="State")
master_df = pd.merge(master_df, od_2015, on="State")
master_df = pd.merge(master_df, od_2016, on="State")
master_df = pd.merge(master_df, od_2017, on="State")
master_df = pd.merge(master_df, rx_2013, on="State")
master_df = pd.merge(master_df, rx_2014, on="State")
master_df = pd.merge(master_df, rx_2015, on="State")
master_df = pd.merge(master_df, rx_2016, on="State")
master_df = pd.merge(master_df, rx_2017, on="State")
master_df = pd.merge(master_df, pop, on="State")

In [5]:
# drop unwanted columns
clean_df = master_df.drop(['2014Rate', '2014Range', '2013Rate',
        '2013Range', 'Change', 'Significant', 'Range', 'Rate',
        'range_x', 'rate_x', 'range_y', 'rate_y','State_Name_x', 'State_Name_y',
       'State_Name_x', 'State_Name_y', 'State_Name',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5','Unnamed: 11'], axis=1)

In [6]:
# re-order columns
final_df = clean_df[['Region','State','RX_2013', 'OD_2013', 'Pop_2013', 'RX_2014', 'OD_2014','Pop_2014', 
        'RX_2015', 'OD_2015', 'Pop_2015','RX_2016', 'OD_2016','Pop_2016', 'RX_2017','OD_2017','Pop_2017']]

In [61]:
final_df.head(10)

,Region,State,RX_2013,OD_2013,Pop_2013,RX_2014,OD_2014,Pop_2014,RX_2015,OD_2015,Pop_2015,RX_2016,OD_2016,Pop_2016,RX_2017,OD_2017,Pop_2017
0,Far West,AK,63.7,105,"737,045",62.7,124,"736,307",60.8,122,"737,547",58.9,128,"741,504",52.0,147,"739,786"
1,Southeast,AL,142.4,598,"4,830,460",135.2,723,"4,842,481",125.0,736,"4,853,160",121.0,756,"4,864,745",107.2,835,"4,875,120"
2,Southeast,AR,120.9,319,"2,959,549",123.2,356,"2,967,726",117.2,392,"2,978,407",114.6,401,"2,990,410",105.4,446,"3,002,997"
3,Southwest,AZ,80.4,"1,222","6,634,999",79.7,"1,211","6,733,840",75.5,"1,274","6,833,596",70.2,"1,382","6,945,452",61.2,"1,532","7,048,876"
4,Far West,CA,54.4,"4,452","38,280,824",52.7,"4,521","38,625,139",47.7,"4,659","38,953,142",44.8,"4,654","39,209,127",39.5,"4,868","39,399,349"
5,Rocky Mountain,CO,71.2,846,"5,270,482",69.6,899,"5,351,218",65.1,869,"5,452,107",59.8,942,"5,540,921",52.9,"1,015","5,615,902"
6,New England,CT,67.4,582,"3,594,915",66.0,623,"3,594,783",62.3,800,"3,587,509",55.9,971,"3,578,674",48.0,"1,072","3,573,880"
7,Mideast,DC,41.1,102,"650,431",40.1,96,"662,513",35.7,125,"675,254",32.5,269,"686,575",28.5,310,"695,691"
8,Mideast,DE,92.7,166,"923,638",91.0,189,"932,596",84.4,198,"941,413",79.2,282,"949,216",68.3,338,"957,078"
9,Southeast,FL,73.5,"2,474","19,563,166",71.4,"2,634","19,860,330",67.1,"3,228","20,224,249",66.6,"4,728","20,629,982",60.9,"5,088","20,976,812"

In [62]:
export_csv = final_df.to_csv ("cg_final_df.csv", index = None, header=True)